In [2]:
import numpy as np

In [3]:
X = np.array([
        [2,3],
        [2,4],
        [6,3],
        [5,1],
        [1,5],
    ])

In [4]:
W1 = np.array([
    [0.5, 0.1],
    [0.2, 0.4]
])

In [5]:
b1 = np.array([
    [0.1, 0.2]
])

In [6]:
def relu(x):
    return np.maximum(0,x)

In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [8]:
Z1 = X @ W1 + b1

In [9]:
Z1

array([[1.7, 1.6],
       [1.9, 2. ],
       [3.7, 2. ],
       [2.8, 1.1],
       [1.6, 2.3]])

In [10]:
Z1.shape

(5, 2)

In [11]:
A1 = relu(Z1)

In [12]:
A1.shape

(5, 2)

In [13]:
A1

array([[1.7, 1.6],
       [1.9, 2. ],
       [3.7, 2. ],
       [2.8, 1.1],
       [1.6, 2.3]])

In [14]:
W2 = np.array([
    [0.2],
    [0.3]
])
W2.shape

(2, 1)

In [15]:
b2 = np.array([0.1])

In [16]:
Z2 = A1 @ W2 + b2
Z2

array([[0.92],
       [1.08],
       [1.44],
       [0.99],
       [1.11]])

In [17]:
output = sigmoid(Z2)
output

array([[0.71504211],
       [0.74649398],
       [0.80845465],
       [0.72908792],
       [0.75212911]])

In [ ]:
X = np.array([[2, 3]])   # one sample, two features
y = np.array([[1]])      # actual class


def relu(x):
    return np.maximum(0, x)


def relu_derivative(x):
    return (x > 0).astype(float)


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

W1 = np.array([
    [0.5, 0.1],
    [0.2, 0.4]
], dtype=float)

b1 = np.array([
    [0.1, 0.2]
], dtype=float)


Z1 = X @ W1 + b1
A1 = relu(Z1)

W2 = np.array([
    [0.2],
    [0.3]
], dtype=float)

b2 = np.array([
    [0.1]
], dtype=float)

Z2 = A1 @ W2 + b2
y_hat = sigmoid(Z2)


print("Z1 =", Z1)
print("A1 =", A1)
print("Z2 =", Z2)
print("Prediction =", y_hat)


loss = np.mean(-(y * np.log(y_hat) +
         (1 - y) * np.log(1 - y_hat)))

print("Loss =", loss)


dZ2 = y_hat - y

dW2 = A1.T @ dZ2

db2 = dZ2

dA1 = dZ2 @ W2.T

dZ1 = dA1 * relu_derivative(Z1)


dW1 = X.T @ dZ1

db1 = dZ1

learning_rate = 0.1
iterations=10

for _ in range(iterations):

    dZ2 = y_hat - y

    dW2 = A1.T @ dZ2

    db2 = dZ2

    dA1 = dZ2 @ W2.T

    dZ1 = dA1 * relu_derivative(Z1)


    dW1 = X.T @ dZ1

    db1 = dZ1

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1

    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

    Z1 = X @ W1 + b1
    A1 = relu(Z1)

    Z2 = A1 @ W2 + b2


y_hat = sigmoid(Z2)


print("New prediction =", y_hat)

Z1 = [[1.7 1.6]]
A1 = [[1.7 1.6]]
Z2 = [[0.92]]
Prediction = [[0.71504211]]
Loss = [[0.33541385]]
New prediction = [[0.99923255]]


In [39]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(
    activation="relu",
    max_iter=1000,
    hidden_layer_sizes=(2,),
    random_state=42,
)
model.fit(X,y)

/home/ankit/Projects/class/kathfordml-csit2080/venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1223: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(2,)"
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",1000
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary <random_state>`.",42
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'adam'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",0.0001
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.001
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"shuffle shuffle: bool, default=TrueWhether to shuffle samples in each iteration. Only used whensolver='sgd' or 'adam'.",True


In [44]:
model.predict([[2,3],[3,2]])

array([1, 1])

In [45]:
model.coefs_

[array([[ 0.0092047 ,  0.8350467 ],
        [ 0.88476235, -0.0272611 ]]),
 array([[-1.73227575],
        [ 0.83120776]])]

In [46]:
model.intercepts_

[array([-0.5260614 , -1.11156247]), array([-0.00231311])]