In [1]:
import torch

In [6]:
x = torch.tensor([1,2,3], dtype=torch.float32)

In [7]:
x.dtype

torch.float32

In [11]:
torch.zeros(3,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [12]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [13]:
torch.rand(4,1)

tensor([[0.5930],
        [0.5604],
        [0.7112],
        [0.1955]])

In [14]:
torch.randn(4,1)

tensor([[ 0.0294],
        [-0.2928],
        [-2.0413],
        [ 1.2299]])

In [15]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])

In [17]:
a + b

tensor([2, 4, 6])

In [18]:
a - b

tensor([0, 0, 0])

In [19]:
a * b

tensor([1, 4, 9])

In [20]:
a @ b

tensor(14)

In [21]:
a

tensor([1, 2, 3])

In [22]:
a.reshape(1,3)

tensor([[1, 2, 3]])

In [23]:
a.reshape([3,1])

tensor([[1],
        [2],
        [3]])

In [24]:
x = torch.tensor(3., requires_grad=True)
y = x ** 2

y.backward()
print(x.grad)

tensor(6.)


In [25]:
x1 = torch.tensor(2., requires_grad=True)
x2 = torch.tensor(3., requires_grad=True)

w1 = torch.tensor(0.5, requires_grad=True)
w2 = torch.tensor(0.2, requires_grad=True)

b = torch.tensor(0.1, requires_grad=True)

y = w1 * x1 + w2 * x2 + b

y.backward()

In [26]:
print(w1.grad)
print(w2.grad)
print(b.grad)

tensor(2.)
tensor(3.)
tensor(1.)


In [28]:
import torch.nn as nn

In [29]:
relu = nn.ReLU()

In [37]:
X = torch.tensor([[2, 3]], dtype=torch.float32)   # one sample, two features
y = torch.tensor([[1]], dtype=torch.float32)      # actual class
W1 = torch.tensor([
    [0.5, 0.1],
    [0.2, 0.4]
], dtype=torch.float32, requires_grad=True)

b1 = torch.tensor([
    [0.1, 0.2]
], dtype=torch.float32, requires_grad=True)

Z1 = X @ W1 + b1
A1 = relu(Z1)

W2 = torch.tensor([
    [0.2],
    [0.3]
], dtype=torch.float32, requires_grad=True)

b2 = torch.tensor([
    [0.1]
], dtype=torch.float32, requires_grad=True)

Z2 = A1 @ W2 + b2
y_hat = torch.sigmoid(Z2)


In [38]:
loss_fn = torch.nn.BCELoss()
loss = loss_fn(y_hat, y)

In [39]:
loss.backward()

In [40]:
print(w1.grad)
print(w2.grad)
print(b1.grad)
print(b2.grad)

tensor(2.)
tensor(3.)
tensor([[-0.0570, -0.0855]])
tensor([[-0.2850]])
