In [1]:
marks = [40, 50, 60, 40, 50]

new_marks = []
for m in marks:
    new_marks.append(m + 5)

print(new_marks)

[45, 55, 65, 45, 55]


In [2]:
new_marks2 = [m + 5 for m in marks]

print(new_marks2)

[45, 55, 65, 45, 55]


In [7]:
a = [1,2,3]
b = [4,5,6]

print(a + b)

[1, 2, 3, 4, 5, 6]


In [4]:
print(a * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [5]:
import numpy as np

In [8]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
print(2*a)

[2 4 6]


In [10]:
b = np.array([4,5,6])
print(a + b)

[5 7 9]


In [11]:
type(a)

numpy.ndarray

In [12]:
print(a)

[1 2 3]


In [14]:
print(a + 5)

[6 7 8]


In [15]:
print(a ** 2)

[1 4 9]


In [ ]:
n = 1_000_0000
import time
time_list_start = time.time()
lst = list(range(n))
new_lst = [m + 5 for m in lst]
time_list_end = time.time()
print(f"time taken in list: {time_list_end - time_list_start}")
time_arr_start = time.time()
arr = np.arange(n)
new_arr = arr + 5
time_arr_end = time.time()
print(f"time taken in arr: {time_arr_end - time_arr_start}")



time taken in list: 0.3638572692871094
time taken in arr: 0.019773483276367188


In [23]:
print(a.shape)

(3,)


In [24]:
b = np.array([
    [1,2,3],
    [4,5,6]
])

print(b.shape)

(2, 3)


In [ ]:
print(a.ndim)
print(b.ndim)

1
2


In [26]:
print(a.dtype)

int64


In [27]:
lst = [1,2,3,4,5]

arr = np.array(lst)

import sys

print(sys.getsizeof(lst))

print(arr.nbytes)

104
40


In [29]:
a = np.array([10,20,30,40,50,60])

print(a[0])
print(a[-1])

10
60


In [32]:
print(a[1:3])
type(a[1:3])

[20 30]


numpy.ndarray

In [33]:
lst = [10,20,30,40,50,60]

print(lst[1:3])
type(lst[1:3])

[20, 30]


list

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])